### PR TITLE
feat: cover more formats for eve multibuy import

### PR DESCRIPTION
**Pull request by madetara**
So far the only supported format for eve multibuy was
`<name of the item><tab character><number><whatever>`
Even though EVE multibuy supports a lot more formats, such as
`<item name><space><number>`
`<item name><space>x<number>`
I tried to cover all of these cases

I encountered this problem while trying to use "Multibuy" function from https://evecookbook.com
Cookbok provides multibuy list in the following format
```
Tritanium x100
Isogen x50
```
Which jeveassets failed to recognise, but it works in EVE

It's been a long time since I used Java, but hopefully code is not too bad
My only concern is usage of `Pair` from Kotlin, because I don't know whether it works with default JRE/JDK distribution

### CODE REVIEW

**Comment by GoldenGnu** [comment]
Thank you very much for the PR, I really appreciate it! 👍 

A few questions:
1) Does it ever happen that the delimiter between the item name and the number is just a single space?
2) Does the count/number ever come every come before the item name, or can we assume it will be always be the last entry?

**Comment by madetara** [comment]
1. Yes, that's the format which evecookbook uses and it works in game

Second question will require some additional elaboration

Count is not always the last entry because if you export from multibuy (in game) it will also export buy/sell prices and the game expects that same data can be imported even though prices mean nothing in that case
So it can actually be one of the last three entries
And you actually use that format in [test cases](https://github.com/GoldenGnu/jeveassets/blob/fd627dc077b5f215254a29eb4d9c31d66b2d2534/src/test/java/net/nikr/eve/jeveasset/gui/tabs/stockpile/ImportEveMultibuyTest.java#L35):
```
100MN Afterburner II	1	-	-
Dominix	1	-	-
Capacitor Power Relay II	1	-	-
Hammerhead II	10	1.189.997,05	11.899.970,50
```

However I doubt that count can come before item name, though I will check it in game later, just to be sure

**Comment by GoldenGnu** [comment]
Thanks!
`findCountIndex` method is working perfectly no matter what I throw at it, really good job with that!
I have had a really hard time finding a reliable way to find the count number, due to item names like `X5 Enduring Stasis Webifier` and `30,000 Skill Points`

If you could please add yourself to the https://github.com/GoldenGnu/jeveassets/blob/master/credits.txt#L19 and https://github.com/GoldenGnu/jeveassets/blob/master/src/main/java/net/nikr/eve/jeveasset/gui/dialogs/AboutDialog.java#L92 that would be great. You can use your real name, eve name, an alias, or any combination thereof.

**Comment by madetara** [comment]
> However I doubt that count can come before item name, though I will check it in game later, just to be sure

I just checked it and item count indeed can be before the item name, so this all work
```
1 Veldspar
1	Spodumain
x10 Tritanium
```
I'll try to address it today

**Comment by madetara** [comment]
> I have had a really hard time finding a reliable way to find the count number, due to item names like X5 Enduring Stasis Webifier and 30,000 Skill Points

I've made an assumption that since CCP, too, has to parse it somehow, there should be no collisions with the regex I used `^x?\d+$` but I'll look through item tables to double-check

**Comment by GoldenGnu** [comment]
I'm be perfectly happy with just how it's implemented now, handling everything where the count is after the item name.
The shopping list import already handle x[number] [item name], so that only leaves [number] [item name].
It would be great if you're ably to do it, but, this is already a great addition!

Please also remember to add yourself to the credits.
It would also be helpful if you updated from remote, to fix the test failures, that is not related to this PR.

Thank again for this great contribution! 👍

**Comment by madetara** [comment]
I added support for entries whereitem count comes before item name and tests for such cases
Rebased on main branch
Added myself to contributors with my github name and EVE name

I also greped item list and it seems like there really is no collisions with item count format I use

**Comment by GoldenGnu** [comment]
This is ready to merge. I will merge it when I have some free time. Thank you for your contribution!

In case you're interested in contributing any more, please join the jEveAssets discord server: https://discord.gg/8kYZvbM

**Comment by madetara** [comment]
Thank you 🎉 
I'll consider joining the dev team, but I'm not really a Java person

**Comment by GoldenGnu** [comment]
The quality of you code doesn’t show any signs of you not being a Java person.
The dev team is currently just 2-3 people including myself. Everyone work on the stuff they want and contribute as much or as little as life allow.

**Comment by GoldenGnu** [comment]
Released in 7.0.0
@madetara if you could please join the discord https://discord.gg/8kYZvbM and PM me, as I would very much like to reward you a eve partner skin for your work

**Pull request merged**
