### PR TITLE
Code: Added constants

### PR DESCRIPTION
**Pull request by crmason2**
Add constants for skill IDs to be used instead of hard coded values. Commented out all of the currently unused skills although IDs are correct.

### CODE REVIEW

**Comment by AnrDaemon** [comment]
I suggest a generator from data export rather than manually hardcoded values.

**Comment by crmason2** [comment]
So what we could do is generate a property file from the data export and have the constants use those properties instead. I don't think compiling a new class on the off change that and ID value changes would be very dynamic. This way we could update the IDs without pushing a new build. Also since it's just name and ID I think a more complicated structure like XML is probably overkill.

The main problem I see with that though is that while the IDs for skills are very static (I compared the first instance of items.xml I could find in the repo with the latest) the names of skills are not.

I found at least 100 name changes, dozens of skills added and a few dozen removed. But I could not find a single instance were a skill ID changed.

**Comment by GoldenGnu** [comment]
I don't like it, sorry.
Skills are dynamic data (as I have said before).
Having skill constant that are used does make sense to me.
Having constants for every possible skill does not make sense to me, at all.
It will become incomplete and/or wrong as soon as any skill change, and they will!

Also, I would prefer an `enum`, so it can iterated over it. With something like getID() to get the id.
That would make testing the constants possible, and I think that would be very useful.

**Comment by crmason2** [comment]
Would we prefer to have the enum part of RawSkill or in a separate class?

**Comment by GoldenGnu** [comment]
I prefer it in a separate class

**Comment by GoldenGnu** [comment]
If we do decide to include all skills, the class will need to be updated regularly.
That means it should be generated by https://github.com/GoldenGnu/jeveasset-creator project.

**Comment by crmason2** [comment]
Generating it will be a nightmare with the amount of name changes skills have. The issue I see with using enum is Java doesn't let you set the ordinal of the enum, so we can't set the ordinal to be the skill ID, We can make a custom value for the enum but that can't be used in a switch since it isn't "constant". I think I'm just going to scrap this for now since what was a simple code readability fix has gotten more complicated than I envisioned.

**Pull request closed without merging**
